//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdmissionCommitteeModule.ServerWebApplication.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджет.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее среднее образование.
        /// </summary>
        internal static string CommonMiddleSchool {
            get {
                return ResourceManager.GetString("CommonMiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заочная форма обучения.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачислить.
        /// </summary>
        internal static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очная форма обучения.
        /// </summary>
        internal static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высшее образование.
        /// </summary>
        internal static string Higher {
            get {
                return ResourceManager.GetString("Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контракт с физическим лицом.
        /// </summary>
        internal static string IndividualEntities {
            get {
                return ResourceManager.GetString("IndividualEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контракт с юридическим лицом.
        /// </summary>
        internal static string LegalEntities {
            get {
                return ResourceManager.GetString("LegalEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее полное образование.
        /// </summary>
        internal static string MiddleSchool {
            get {
                return ResourceManager.GetString("MiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не зачислять.
        /// </summary>
        internal static string NotEnroll {
            get {
                return ResourceManager.GetString("NotEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не запрошено на подпись.
        /// </summary>
        internal static string NotRequested {
            get {
                return ResourceManager.GetString("NotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не рассмотренно.
        /// </summary>
        internal static string NotСonsidered {
            get {
                return ResourceManager.GetString("NotСonsidered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается подпись.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписано.
        /// </summary>
        internal static string Signed {
            get {
                return ResourceManager.GetString("Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее специальное образование.
        /// </summary>
        internal static string TechnicalSchool {
            get {
                return ResourceManager.GetString("TechnicalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
