//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Член приемной комиссии.
        /// </summary>
        public static string AdmissionCommitteeMember {
            get {
                return ResourceManager.GetString("AdmissionCommitteeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не может быть не указано или содержать только пробелы..
        /// </summary>
        public static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заместитель директора.
        /// </summary>
        public static string AssociateDirector {
            get {
                return ResourceManager.GetString("AssociateDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджет.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть не указанным..
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0}.{1} не найдено..
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее среднее образование.
        /// </summary>
        public static string CommonMiddleSchool {
            get {
                return ResourceManager.GetString("CommonMiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля {0} и {1} не совподают..
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя получить поле {0}..
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является номером кредитной карты..
        /// </summary>
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success..
        /// </summary>
        public static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or is not public and static..
        /// </summary>
        public static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute.Method was not specified..
        /// </summary>
        public static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional..
        /// </summary>
        public static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the value of type &apos;{0}&apos; to &apos;{1}&apos; as expected by method {2}.{3}..
        /// </summary>
        public static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должно быть публичным..
        /// </summary>
        public static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не верно указано. Проверьте ввод данных..
        /// </summary>
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип не указан..
        /// </summary>
        public static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот тип данных не может быть не указан..
        /// </summary>
        public static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директор.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не указано.  Используйте {1}..
        /// </summary>
        public static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заочная форма обучения.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаменатель.
        /// </summary>
        public static string Divisor {
            get {
                return ResourceManager.GetString("Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является e-mail адресом..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачислить.
        /// </summary>
        public static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение должно быть указано..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; не является перечислением..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не совподает с требуемым расширением файла: {1}.
        /// </summary>
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПТ.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очная форма обучения.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высшее образование.
        /// </summary>
        public static string Higher {
            get {
                return ResourceManager.GetString("Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контракт с физическим лицом.
        /// </summary>
        public static string IndividualEntities {
            get {
                return ResourceManager.GetString("IndividualEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контракт с юридическим лицом.
        /// </summary>
        public static string LegalEntities {
            get {
                return ResourceManager.GetString("LegalEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length..
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано больше элементов поля {0} чем &apos;{1}&apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetadataClassType cannot be null..
        /// </summary>
        public static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее полное образование.
        /// </summary>
        public static string MiddleSchool {
            get {
                return ResourceManager.GetString("MiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLengthAttribute must have a Length value that is zero or greater..
        /// </summary>
        public static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано меньше элементов поля  {0} чем {1}..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПН.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не зачислять.
        /// </summary>
        public static string NotEnroll {
            get {
                return ResourceManager.GetString("NotEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не запрошено на подпись.
        /// </summary>
        public static string NotRequested {
            get {
                return ResourceManager.GetString("NotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не рассмотрено.
        /// </summary>
        public static string NotСonsidered {
            get {
                return ResourceManager.GetString("NotСonsidered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Числитель.
        /// </summary>
        public static string Numerator {
            get {
                return ResourceManager.GetString("Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внебюджет.
        /// </summary>
        public static string OutOfBudget {
            get {
                return ResourceManager.GetString("OutOfBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается подпись.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является номером телефона..
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля {0} должно быть {1}..
        /// </summary>
        public static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value &apos;{0}&apos; must be greater than or equal to the minimum value &apos;{1}&apos;..
        /// </summary>
        public static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum values must be set..
        /// </summary>
        public static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperandType must be set when strings are used for minimum and maximum values..
        /// </summary>
        public static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно быть между {1} {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не соответствует формату {1}..
        /// </summary>
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pattern must be set to a valid regular expression..
        /// </summary>
        public static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} обязаятельно..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СБ.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер расписания.
        /// </summary>
        public static string ScheduleManager {
            get {
                return ResourceManager.GetString("ScheduleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписано.
        /// </summary>
        public static string Signed {
            get {
                return ResourceManager.GetString("Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length must be a nonnegative integer..
        /// </summary>
        public static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно быть строкой короче чем {1} символов..
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно быть строкой с длиной между {2} и {1} символами..
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВС.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учитель.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее специальное образование.
        /// </summary>
        public static string TechnicalSchool {
            get {
                return ResourceManager.GetString("TechnicalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЧТ.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВТ.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; is not a string. Every key control parameter must be a string..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} is null. Every key control parameter must be a string..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; occurs more than once..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of control parameters must be even..
        /// </summary>
        public static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является интернет ссылкой..
        /// </summary>
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансия.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ErrorMessageString or ErrorMessageResourceName must be set, but not both..
        /// </summary>
        public static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context)..
        /// </summary>
        public static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute..
        /// </summary>
        public static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on resource type &apos;{1}&apos; is not a string type..
        /// </summary>
        public static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; does not have an accessible static property named &apos;{1}&apos;..
        /// </summary>
        public static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не правильно указано..
        /// </summary>
        public static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidationContext for the type &apos;{0}&apos;, member name &apos;{1}&apos; must provide the MethodInfo..
        /// </summary>
        public static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &apos;{0}&apos; already exists in the container..
        /// </summary>
        public static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance provided must match the ObjectInstance on the ValidationContext supplied..
        /// </summary>
        public static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля {0} должно быть &apos;{1}&apos;..
        /// </summary>
        public static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СР.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочая.
        /// </summary>
        public static string Workings {
            get {
                return ResourceManager.GetString("Workings", resourceCulture);
            }
        }
    }
}
