// <auto-generated />
using Application.Specialities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Specialities.Data.Migrations
{
    [DbContext(typeof(SpecialitiesDbContext))]
    [Migration("20220520135823_AssignSubjectsToSpecialities")]
    partial class AssignSubjectsToSpecialities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Specialities.Data.Speciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int?>("EntranceTest")
                        .HasColumnType("integer")
                        .HasColumnName("entrance_test");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_speciality");

                    b.ToTable("speciality", (string)null);
                });

            modelBuilder.Entity("Application.Specialities.Data.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<long>("SpecialityId")
                        .HasColumnType("bigint")
                        .HasColumnName("speciality_id");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("SpecialityId")
                        .HasDatabaseName("ix_subject_speciality_id");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("Application.Specialities.Data.Subject", b =>
                {
                    b.HasOne("Application.Specialities.Data.Speciality", "Speciality")
                        .WithMany("Subjects")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_speciality_speciality_id");

                    b.OwnsMany("Application.Specialities.Data.Semester", "Semesters", b1 =>
                        {
                            b1.Property<long>("SubjectId")
                                .HasColumnType("bigint")
                                .HasColumnName("subject_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Hours")
                                .HasColumnType("integer")
                                .HasColumnName("hours");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.HasKey("SubjectId", "Id")
                                .HasName("pk_semester");

                            b1.ToTable("semester", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubjectId")
                                .HasConstraintName("fk_semester_subject_subject_id");
                        });

                    b.Navigation("Semesters");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Application.Specialities.Data.Speciality", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
